In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'Understand the meaning of words',
      'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [4]:
###Vocabulary size
voc_size=10000

One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8406, 4433, 565, 6312], [8406, 4433, 565, 595], [8406, 5376, 565, 5763], [6099, 4172, 5905, 645, 3081], [6099, 4172, 5905, 645, 1870], [1930, 8406, 5581, 565, 5048], [5197, 6726, 6172, 645]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8406 4433  565 6312]
 [   0    0    0    0 8406 4433  565  595]
 [   0    0    0    0 8406 5376  565 5763]
 [   0    0    0 6099 4172 5905  645 3081]
 [   0    0    0 6099 4172 5905  645 1870]
 [   0    0    0 1930 8406 5581  565 5048]
 [   0    0    0    0 5197 6726 6172  645]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 4s 4s/step
[[[-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
    2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
    4.44468297e-02 -5.11347130e-03]
  [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
    2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
    4.44468297e-02 -5.11347130e-03]
  [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
    2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
    4.44468297e-02 -5.11347130e-03]
  [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
    2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
    4.44468297e-02 -5.11347130e-03]
  [-1.65518522e-02  9.79916006e-03 -2.31505390e-02  3.33089866e-02
   -1.29423365e-02 -4.59769033e-02 -3.63387577e-02  4.18091938e-03
    2.26638056e-02  3.41090672e-02]
  [-1.60858147e-02  2.36896537e-02 -4.58543561e-02 -1.93987843e-02
    1.86474808e-02  3.12131979e-0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8406, 4433,  565, 6312])

In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 33ms/step
[[-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
   2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
   4.44468297e-02 -5.11347130e-03]
 [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
   2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
   4.44468297e-02 -5.11347130e-03]
 [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
   2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
   4.44468297e-02 -5.11347130e-03]
 [-4.75710519e-02 -6.24790043e-03 -1.98393594e-02 -4.40339707e-02
   2.64601223e-02 -6.92255422e-03  4.11035083e-02 -1.35128573e-03
   4.44468297e-02 -5.11347130e-03]
 [-1.65518522e-02  9.79916006e-03 -2.31505390e-02  3.33089866e-02
  -1.29423365e-02 -4.59769033e-02 -3.63387577e-02  4.18091938e-03
   2.26638056e-02  3.41090672e-02]
 [-1.60858147e-02  2.36896537e-02 -4.58543561e-02 -1.93987843e-02
   1.86474808e-02  3.12131979e-02 -3.32870856e-